export const FETCH_WEATHER_HOURLU_SUCCESS = "FETCH_WEATHER_HOURLU_SUCCESS"
export const FETCH_WEATHER_HOURLU_FAILURE = "FETCH_WEATHER_HOURLU_FAILURE"
export const FETCH_WEATHER_HOURLU_REQUEST = "FETCH_WEATHER_HOURLU_REQUEST"

export const FETCH_WEATHER_DAILY_SUCCESS = "FETCH_WEATHER_DAILY_SUCCESS"
export const FETCH_WEATHER_DAILY_FAILURE = "FETCH_WEATHER_DAILY_FAILURE"
export const FETCH_WEATHER_DAILY_REQUEST = "FETCH_WEATHER_DAILY_REQUEST"

export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS"
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE"
export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST"

export const FETCH_SENSOR_VALUES_SUCCESS = "FETCH_SENSOR_VALUES_SUCCESS"
export const FETCH_SENSOR_VALUES_FAILURE = "FETCH_SENSOR_VALUES_FAILURE"
export const FETCH_SENSOR_VALUES_REQUEST = "FETCH_SENSOR_VALUES_REQUEST"

export const FETCH_GRAPHS_DATA_SUCCESS = "FETCH_GRAPHS_DATA_SUCCESS"
export const FETCH_GRAPHS_DATA_FAILURE = "FETCH_GRAPHS_DATA_FAILURE"
export const FETCH_GRAPHS_DATA_REQUEST = "FETCH_GRAPHS_DATA_REQUEST"

export const FETCH_SWITCHABLE_OPTIONS_SUCCESS = "FETCH_SWITCHABLE_OPTIONS_SUCCESS"
export const FETCH_SWITCHABLE_OPTIONS_FAILURE = "FETCH_SWITCHABLE_OPTIONS_FAILURE"
export const FETCH_SWITCHABLE_OPTIONS_REQUEST = "FETCH_SWITCHABLE_OPTIONS_REQUEST"
